---
- name: clear env
  hosts: qb_rhel
  gather_facts: false
  tasks:
  - name: stop mariadb
    command: "systemctl stop mariadb"
  - name: uninstall mariadb
    command: "yum -y erase mariadb-server"
  - name: stop apache
    command: "systemctl stop httpd"
  - name: uninstall apache
    command: "yum -y erase httpd"
...
